services:
  - type: web
    name: resume-analyzer
    env: python
    buildCommand: |
      ./setup.sh
      pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port=$PORT --server.enableCORS=false
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
